# Generated by Django 5.1.3 on 2024-12-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_projects',
        ),
    ]
