# Generated by Django 5.1.4 on 2024-12-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_current_projects'),
        ('intra_client', '0002_remove_questrank_quest_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='intra_client.questrank'),
        ),
    ]
