# Generated by Django 5.1.3 on 2024-12-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank',
            new_name='quest_rank',
        ),
    ]
