# Generated by Django 5.1.3 on 2024-12-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_rank_user_quest_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quest_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
