# Generated by Django 5.1.6 on 2025-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_quest_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
