# Generated by Django 5.1.6 on 2025-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
