# Generated by Django 5.1.4 on 2025-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_location',
            field=models.BooleanField(default=False),
        ),
    ]
