# Generated by Django 5.2 on 2025-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_cancelled_evals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
