# Generated by Django 5.2 on 2025-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
