# Generated by Django 5.2 on 2025-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_blocked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badpeer_score',
            field=models.IntegerField(default=0),
        ),
    ]
