# Generated by Django 5.2 on 2025-05-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_evaluation_state'),
        ('api', '0018_user_weekly_evals'),
    ]

    operations = [
    ]
