# Generated by Django 5.2 on 2025-05-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20250513_1120'),
        ('api', '0019_merge_20250513_1205'),
    ]

    operations = [
    ]
