# Generated by Django 5.2 on 2025-05-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20250513_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, help_text='Filename of the avatar stored in media/avatars/', max_length=100),
        ),
    ]
