# Generated by Django 5.2.1 on 2025-06-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_last_campus_login_user_last_campus_logout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_pass',
            field=models.BooleanField(default=False),
        ),
    ]
