# Generated by Django 5.2.1 on 2025-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_block_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block_pass',
            field=models.BooleanField(default=True),
        ),
    ]
