# Generated by Django 5.2.1 on 2025-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_user_block_pass_remove_user_weekly_evals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('block', 'Block'), ('unblock', 'Unblock')], max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
