# Generated by Django 5.2.3 on 2025-06-24 10:09

from django.db import migrations

def populate_team_string(apps, schema_editor):
    MyModel = apps.get_model('api', 'evaluation')
    for obj in MyModel.objects.all():
        if isinstance(obj.team, list):
            obj.team_str = ", ".join(obj.team)
        else:
            obj.team_str = ""
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_evaluation_team_str'),
    ]

    operations = [
        migrations.RunPython(populate_team_string),
    ]
