# Generated by Django 5.1.4 on 2024-12-09 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.IntegerField()),
                ('quest_users', models.ManyToManyField(related_name='quest_ranks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
