# Generated by Django 5.1.4 on 2024-12-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intra_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questrank',
            name='quest_users',
        ),
    ]
