# Generated by Django 5.1.3 on 2024-12-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_quest_rank'),
        ('intra_client', '0002_remove_questrank_quest_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestRank',
        ),
    ]
