CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_verified BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    birth_date DATE,
    location_source TEXT NOT NULL DEFAULT '',
    location_name TEXT NOT NULL DEFAULT '',
    location_consent_at TIMESTAMPTZ,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    user_name TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    pending_email TEXT,
    password TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT false,
    gender TEXT NOT NULL DEFAULT '',
    preferences TEXT NOT NULL DEFAULT 'Everyone',
    bio TEXT NOT NULL DEFAULT '',
    interests JSONB NOT NULL DEFAULT '[]'::jsonb,
    avatar TEXT NOT NULL DEFAULT '',

    CONSTRAINT users_gender_valid CHECK (gender IN ('', 'Male', 'Female', 'Other')),
    CONSTRAINT users_preferences_valid CHECK (preferences IN ('Male', 'Female', 'Other', 'Everyone')),
    CONSTRAINT users_user_name_not_blank CHECK (btrim(user_name) <> ''),
    CONSTRAINT users_first_name_not_blank CHECK (btrim(first_name) <> ''),
    CONSTRAINT users_last_name_not_blank CHECK (btrim(last_name) <> ''),
    CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT users_password_not_blank CHECK (btrim(password) <> ''),
    CONSTRAINT users_interests_is_array CHECK (jsonb_typeof(interests) = 'array'),
    CONSTRAINT users_latitude_valid CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT users_longitude_valid CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT users_location_source_valid CHECK (location_source IN ('', 'gps', 'manual')),
    CONSTRAINT users_location_state_valid CHECK (
        (location_source = '' AND location_name = '' AND location_consent_at IS NULL AND latitude IS NULL AND longitude IS NULL)
        OR (location_source = 'gps' AND btrim(location_name) = '' AND location_consent_at IS NOT NULL AND latitude IS NOT NULL AND longitude IS NOT NULL)
        OR (location_source = 'manual' AND btrim(location_name) <> '' AND location_consent_at IS NULL AND latitude IS NOT NULL AND longitude IS NOT NULL)
    )
);

CREATE UNIQUE INDEX users_pending_email_unique_idx ON users (pending_email) WHERE pending_email IS NOT NULL;