CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_name TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT false,
    gender TEXT NOT NULL DEFAULT '',
    preferences TEXT NOT NULL DEFAULT '',
    bio TEXT NOT NULL DEFAULT '',
    interests JSONB NOT NULL DEFAULT '[]'::jsonb,
    avatar TEXT NOT NULL DEFAULT '',

    CONSTRAINT users_user_name_not_blank CHECK (btrim(user_name) <> ''),
    CONSTRAINT users_first_name_not_blank CHECK (btrim(first_name) <> ''),
    CONSTRAINT users_last_name_not_blank CHECK (btrim(last_name) <> ''),
    CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT users_password_not_blank CHECK (btrim(password) <> ''),
    CONSTRAINT users_interests_is_array CHECK (jsonb_typeof(interests) = 'array')
);