CREATE TABLE IF NOT EXISTS photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url TEXT NOT NULL,

    CONSTRAINT photos_url_not_blank CHECK (btrim(url) <> '')
);

CREATE INDEX IF NOT EXISTS photos_user_id_idx on photos(user_id);