CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_one_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_two_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT conversations_users_are_different CHECK (user_one_id <> user_two_id),
    CONSTRAINT conversations_users_are_ordered CHECK (user_one_id < user_two_id),
    CONSTRAINT conversations_user_pair_unique UNIQUE (user_one_id, user_two_id)
);

CREATE INDEX IF NOT EXISTS conversations_user_two_id_idx
    ON conversations(user_two_id);