CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    read_at TIMESTAMPTZ,

    CONSTRAINT chat_messages_users_are_different CHECK (sender_id <> recipient_id),
    CONSTRAINT chat_messages_content_not_blank CHECK (btrim(content) <> '')
);

CREATE INDEX IF NOT EXISTS chat_messages_conversation_created_idx ON chat_messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS chat_messages_recipient_unread_idx ON chat_messages(recipient_id) WHERE read_at is NULL;
