CREATE TABLE profile_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    decision TEXT NOT NULL,

    CONSTRAINT profile_decisions_users_are_different CHECK (user_id <> target_user_id),
    CONSTRAINT profile_decisions_decision_is_valid CHECK (decision IN ('like', 'dislike')),
    CONSTRAINT profile_decisions_user_target_unique UNIQUE (user_id, target_user_id)
);

CREATE INDEX profile_decisions_target_like_idx ON profile_decisions (target_user_id) WHERE decision = 'like';