CREATE TABLE IF NOT EXISTS profile_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    viewer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    viewed_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT profile_views_users_are_different CHECK (viewer_id <> viewed_user_id),
    CONSTRAINT profile_views_viewer_viewed_unique UNIQUE (viewer_id, viewed_user_id)
);

CREATE INDEX profile_views_viewed_user_updated_idx ON profile_views (viewed_user_id, updated_at DESC, id DESC);
