CREATE TABLE IF NOT EXISTS account_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    purpose TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,

    CONSTRAINT account_tokens_purpose_valid CHECK (purpose IN ('email_verification', 'password_reset'))
);

CREATE INDEX IF NOT EXISTS account_tokens_user_id_idx ON account_tokens(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS account_tokens_one_active_purpose_idx ON account_tokens(user_id, purpose) WHERE used_at IS NULL;