-- +goose Up

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_name TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT false,
    gender TEXT NOT NULL DEFAULT '',
    preferences TEXT NOT NULL DEFAULT '',
    bio TEXT NOT NULL DEFAULT '',
    interests JSONB NOT NULL DEFAULT '[]'::jsonb,
    avatar TEXT NOT NULL DEFAULT '',

    CONSTRAINT users_user_name_not_blank CHECK (btrim(user_name) <> ''),
    CONSTRAINT users_first_name_not_blank CHECK (btrim(first_name) <> ''),
    CONSTRAINT users_last_name_not_blank CHECK (btrim(last_name) <> ''),
    CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT users_password_not_blank CHECK (btrim(password) <> ''),
    CONSTRAINT users_interests_is_array CHECK (jsonb_typeof(interests) = 'array')
);

CREATE TABLE photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url TEXT NOT NULL,

    CONSTRAINT photos_url_not_blank CHECK (btrim(url) <> '')
);

CREATE INDEX photos_user_id_idx on photos(user_id);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_one_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_two_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT conversations_users_are_different CHECK (user_one_id <> user_two_id),
    CONSTRAINT conversations_users_are_ordered CHECK (user_one_id < user_two_id),
    CONSTRAINT conversations_user_pair_unique UNIQUE (user_one_id, user_two_id)
);

CREATE INDEX conversations_user_two_id_idx
    ON conversations(user_two_id);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    read_at TIMESTAMPTZ,

    CONSTRAINT chat_messages_users_are_different CHECK (sender_id <> recipient_id),
    CONSTRAINT chat_messages_content_not_blank CHECK (btrim(content) <> '')
);

CREATE INDEX chat_messages_conversation_created_idx ON chat_messages(conversation_id, created_at);
CREATE INDEX chat_messages_recipient_unread_idx ON chat_messages(recipient_id) WHERE read_at IS NULL;

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    type TEXT NOT NULL DEFAULT 'notification',
    title TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    read_at TIMESTAMPTZ,

    CONSTRAINT notifications_type_not_blank CHECK (btrim(type) <> ''),
    CONSTRAINT notification_message_not_blank CHECK (btrim(message) <> ''),
    CONSTRAINT notifications_data_is_object CHECK (jsonb_typeof(data) = 'object')
);

CREATE INDEX notifications_user_created_idx ON notifications (user_id, created_at DESC);
CREATE INDEX notifications_user_unread_idx ON notifications (user_id) WHERE read_at IS NULL;

-- +goose Down

DROP TABLE notifications;
DROP TABLE chat_messages;
DROP TABLE conversations;
DROP TABLE photos;
DROP TABLE users;