-- +goose Up

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_verified BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    birth_date DATE,
    location_source TEXT NOT NULL DEFAULT '',
    location_name TEXT NOT NULL DEFAULT '',
    location_consent_at TIMESTAMPTZ,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    user_name TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    pending_email TEXT,
    password TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT false,
    gender TEXT NOT NULL DEFAULT '',
    preferences TEXT NOT NULL DEFAULT 'Everyone',
    bio TEXT NOT NULL DEFAULT '',
    interests JSONB NOT NULL DEFAULT '[]'::jsonb,
    avatar TEXT NOT NULL DEFAULT '',

    CONSTRAINT users_gender_valid CHECK (gender IN ('', 'Male', 'Female', 'Other')),
    CONSTRAINT users_preferences_valid CHECK (preferences IN ('Male', 'Female', 'Other', 'Everyone')),
    CONSTRAINT users_user_name_not_blank CHECK (btrim(user_name) <> ''),
    CONSTRAINT users_first_name_not_blank CHECK (btrim(first_name) <> ''),
    CONSTRAINT users_last_name_not_blank CHECK (btrim(last_name) <> ''),
    CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT users_password_not_blank CHECK (btrim(password) <> ''),
    CONSTRAINT users_interests_is_array CHECK (jsonb_typeof(interests) = 'array'),
    CONSTRAINT users_latitude_valid CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT users_longitude_valid CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT users_location_source_valid CHECK (location_source IN ('', 'gps', 'manual')),
    CONSTRAINT users_location_state_valid CHECK (
        (location_source = '' AND location_name = '' AND location_consent_at IS NULL AND latitude IS NULL AND longitude IS NULL)
        OR (location_source = 'gps' AND btrim(location_name) = '' AND location_consent_at IS NOT NULL AND latitude IS NOT NULL AND longitude IS NOT NULL)
        OR (location_source = 'manual' AND btrim(location_name) <> '' AND location_consent_at IS NULL AND latitude IS NOT NULL AND longitude IS NOT NULL)
    )
);

CREATE UNIQUE INDEX users_pending_email_unique_idx ON users (pending_email) WHERE pending_email IS NOT NULL;

CREATE TABLE photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url TEXT NOT NULL,

    CONSTRAINT photos_url_not_blank CHECK (btrim(url) <> '')
);

CREATE INDEX photos_user_id_idx on photos(user_id);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_one_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_two_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT conversations_users_are_different CHECK (user_one_id <> user_two_id),
    CONSTRAINT conversations_users_are_ordered CHECK (user_one_id < user_two_id),
    CONSTRAINT conversations_user_pair_unique UNIQUE (user_one_id, user_two_id)
);

CREATE INDEX conversations_user_two_id_idx
    ON conversations(user_two_id);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    read_at TIMESTAMPTZ,

    CONSTRAINT chat_messages_users_are_different CHECK (sender_id <> recipient_id),
    CONSTRAINT chat_messages_content_not_blank CHECK (btrim(content) <> '')
);

CREATE INDEX chat_messages_conversation_created_idx ON chat_messages(conversation_id, created_at);
CREATE INDEX chat_messages_recipient_unread_idx ON chat_messages(recipient_id) WHERE read_at IS NULL;

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    type TEXT NOT NULL DEFAULT 'notification',
    title TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    read_at TIMESTAMPTZ,

    CONSTRAINT notifications_type_not_blank CHECK (btrim(type) <> ''),
    CONSTRAINT notification_message_not_blank CHECK (btrim(message) <> ''),
    CONSTRAINT notifications_data_is_object CHECK (jsonb_typeof(data) = 'object')
);

CREATE INDEX notifications_user_created_idx ON notifications (user_id, created_at DESC);
CREATE INDEX notifications_user_unread_idx ON notifications (user_id) WHERE read_at IS NULL;

CREATE TABLE profile_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    decision TEXT NOT NULL,

    CONSTRAINT profile_decisions_users_are_different CHECK (user_id <> target_user_id),
    CONSTRAINT profile_decisions_decision_is_valid CHECK (decision IN ('like', 'dislike')),
    CONSTRAINT profile_decisions_user_target_unique UNIQUE (user_id, target_user_id)
);

CREATE INDEX profile_decisions_target_like_idx ON profile_decisions (target_user_id) WHERE decision = 'like';
CREATE UNIQUE INDEX notifications_match_pair_unique_idx ON notifications (user_id, sender_id) WHERE type = 'match';

CREATE TABLE profile_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    viewer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    viewed_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT profile_views_users_are_different CHECK (viewer_id <> viewed_user_id),
    CONSTRAINT profile_views_viewer_viewed_unique UNIQUE (viewer_id, viewed_user_id)
);

CREATE INDEX profile_views_viewed_user_updated_idx ON profile_views (viewed_user_id, updated_at DESC, id DESC);

CREATE TABLE user_blocks (
    blocker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT user_blocks_are_different CHECK (blocker_id <> blocked_user_id),
    CONSTRAINT user_blocks_pair_unique UNIQUE (blocker_id, blocked_user_id)
);

CREATE INDEX user_blocks_blocked_user_id_idx ON user_blocks(blocked_user_id);

CREATE TABLE user_reports (
    reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reported_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT user_reports_users_are_different CHECK (reporter_id <> reported_user_id),
    CONSTRAINT user_reports_pair_unique UNIQUE (reporter_id, reported_user_id)
);

CREATE INDEX user_reports_reported_user_id_idx ON user_reports (reported_user_id);

CREATE TABLE account_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    purpose TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,

    CONSTRAINT account_tokens_purpose_valid CHECK (purpose IN ('email_verification', 'password_reset'))
);

CREATE INDEX account_tokens_user_id_idx ON account_tokens(user_id);
CREATE UNIQUE INDEX account_tokens_one_active_purpose_idx ON account_tokens(user_id, purpose) WHERE used_at IS NULL;

CREATE TABLE auth_sessions (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,

    CONSTRAINT auth_sessions_id_not_blank CHECK (btrim(id) <> ''),
    CONSTRAINT auth_sessions_expiration_valid CHECK (expires_at > created_at)
);

CREATE INDEX auth_sessions_user_active_idx ON auth_sessions(user_id) WHERE revoked_at IS NULL;
CREATE INDEX auth_sessions_expires_at_idx ON auth_sessions(expires_at);
-- +goose Down

DROP TABLE auth_sessions;
DROP TABLE account_tokens;
DROP TABLE user_reports;
DROP TABLE user_blocks;
DROP TABLE profile_views;
DROP TABLE profile_decisions;
DROP TABLE notifications;
DROP TABLE chat_messages;
DROP TABLE conversations;
DROP TABLE photos;
DROP TABLE users;